//프로젝트에서 사용할 게임플레이 Tag 정의
// 규칙
// 1. 입력 제어용 태그 : Input_AAA
// 2. 플레이어 용 태그 : Player_AAA
// 3. 공용 태그 : Shard_AAA
// 4. 적용 태그 : Enemy_AAA
// 5. 상태: Status, 능력: Ability, 이벤트: Event 태그를 붙여서 사용 EX) Player_Ability_AAA

#pragma once

#include "NativeGameplayTags.h"

namespace ShootingGameTags
{
	// Input Tag
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipSMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAR4);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipSMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAR4); 
	
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HoldAction);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HoldAction_Dash);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HoldAction_Zoom);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HoldAction_Fire);

	// Player Tag
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_SMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_SMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_AR4);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_AR4);

	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Zoom);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Fire);

	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_SMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_AR4);

	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_SMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_SMG11);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_AR4);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_AR4);

	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dash);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Zoom);
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_GunFiring);

	// Shared Tag
	SHOOTINGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Fire);
}